name: Test and build the flask user management app
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                ref: master

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run Tests
              run: python -m pytest -v

            - name: Generate Report
              run: python -m pytest --cov-report term-missing --cov=project